# This .yaml cofinguration file contains all variables used by the snakemake pipeline
# DO NOT CHANGE parameter names without changing it in Snakefile as well
# On the other hand, some parameter values have to be inevitably modifed
# **********************************************************************************************************************************

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ DNA MAPPING @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

### 0. General workflow parameters
fastq_directory:
output_directory:
genome_fasta:
bowtie2_idx_prefix:
fastq_suffix: ".fastq.gz"
read_suffix: ['_R1', '_R2']


### 1. FASTQ trimming
cutadapt_trimm_options: ''
fw_adapter_sequence: "CTGTCTCTTATACACATCT"
rv_adapter_sequence: "CTGTCTCTTATACACATCT"
run_fastq_qc: True


### 2. BAM filtering
MAPQ_threshold: 30
remove_other_chromosomes_pattern: "CMV|HBV|HTLV|HPV|SV40|MCV|KSHV|chrUn|random|HCV|HIV|EBV"
